# Generated by Django 6.0.3 on 2026-03-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0005_tenant_alter_companyconfig_options_and_more'),
        ('employees', '0003_department_tenant_employee_tenant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('tenant', 'employee', 'date')},
        ),
    ]
