# Generated by Django 6.0.3 on 2026-03-20 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_unique_together_attendance_tenant_and_more'),
        ('employees', '0004_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='employees.employee'),
        ),
    ]
