# Generated by Django 5.2.1 on 2026-03-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_department_options_alter_employee_options_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Applicable for part-time/contract employees', max_digits=8),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], db_index=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('paid', 'Paid')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['month', 'year', 'status'], name='payroll_pay_month_66b46b_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'year'], name='payroll_pay_employe_f61fd7_idx'),
        ),
    ]
