# Generated by Django 6.0.3 on 2026-03-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_alter_companyconfig_options_and_more'),
        ('payroll', '0002_alter_payroll_created_at_alter_payroll_hours_worked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
    ]
