# Generated by Django 6.0.3 on 2026-03-20 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_department'),
        ('leaves', '0003_leaverequest_tenant_leavetype_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='employees.employee'),
        ),
    ]
