# Generated by Django 5.2.1 on 2026-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('national', 'National Holiday'), ('regional', 'Regional Holiday'), ('company', 'Company Holiday'), ('optional', 'Optional Holiday')], default='national', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_restricted', models.BooleanField(default=False, help_text='Optional/restricted holiday')),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
