# Generated by Django 5.2.1 on 2026-03-14 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('national', 'National Holiday'), ('regional', 'Regional Holiday'), ('company', 'Company Holiday'), ('optional', 'Optional Holiday')], db_index=True, default='national', max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Mark as optional/restricted holiday'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['year', 'holiday_type'], name='holidays_ho_year_50ef0c_idx'),
        ),
    ]
