# Generated by Django 5.2.1 on 2026-03-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_holiday_created_at_holiday_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
