# Generated by Django 6.0.3 on 2026-03-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_alter_companyconfig_options_and_more'),
        ('holidays', '0003_alter_holiday_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('tenant', 'date')},
        ),
    ]
