# Generated by Django 5.2.1 on 2026-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='My Company', max_length=150)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
            options={
                'verbose_name': 'Company Configuration',
                'verbose_name_plural': 'Company Configuration',
            },
        ),
    ]
