# Generated by Django 5.2.1 on 2026-03-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='global_background_color',
            field=models.CharField(default='#f4f6f9', help_text='Hex color code for the main background (e.g. #f4f6f9)', max_length=20),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='global_font_family',
            field=models.CharField(default="'Inter', sans-serif", help_text="Standard CSS font-family string (e.g. 'Roboto', sans-serif)", max_length=50),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='primary_color',
            field=models.CharField(default='#0d6efd', help_text='Hex color code for primary accents and buttons (e.g. #0d6efd)', max_length=20),
        ),
    ]
