# Generated by Django 5.2.1 on 2026-03-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyconfig_global_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='hra_percentage',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='House Rent Allowance percentage (e.g., 40.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='pf_percentage',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Provident Fund deduction percentage (e.g., 12.00)', max_digits=5),
        ),
    ]
